packages:
  - "apps/*"
  - "packages/*"

allowBuilds:
  sharp: true
  unrs-resolver: true
  "@prisma/client": true
  prisma: true
  "@prisma/engines": true
  "@nestjs/core": true
  esbuild: true
  "@scarf/scarf": false
